### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by whmacken** [FLNRO-Smithers-Research/OffSite_Trial_Reporting#2]
- [x] Setup report Sections: 
1. Study Information (Metadata)
- [x] Map of Trial Sites (Probably Mapview with Topo Map) Near top
- [x] Table at start showing seedlot information Type code, Species, Seedlot number, seed source 
location
- [x] Table is trial site information. Convert position to Lat Lon
2. Graphical comparisons:
- [x] Set standard ggplot to theme_few()
- [x] stacked bar as % in condition class
- [x] layout: all species graphs on one row, graph row for each trial
- [x] summary mean across all trials with errorbars for each condition class for seedlot for each species
- [x] Update temperatures to show frost and hard frost (-4).

3. Statistical comparisons
- [x] Compare seedlot types within species (effect of provenance selection)
- [x] Compare all species x seedlot survival and growth between all trials (suitable/unsuitable species)
- [x] Spatial correlation of poor/morbid within individual trials and between sites

4. Appendix 

- [x] raw Data tables
- [x] individual Trial layout in tmap instead of Mapview
